### ISSUE TITLE
Some vehicles are displayed unnecessarily.

### ISSUE THREAD

**Issue by Dragioner** [ImVexed/ThunderView#17]
It shows the race version and YT cup version of vehicles. When they are not accessible to most of the players. Especially since the tank biathlon event is probably not coming back, as it has been scrubbed from all of the Gaijin sites.

**Comment by ImVexed** [comment]
https://github.com/ImVexed/ThunderView/commit/0818c6ada30c0c7f5502448a14162a1e5b1dea50
