### ISSUE TITLE
2S6 missing thermals in the table

### ISSUE THREAD

**Issue by ginyat** [ImVexed/ThunderView#20]
2S6 has two upgrades that change its optics: the first one is like most other vehicles' upgrades (gives it NVD), and the second one is listed as an armour upgrade. The latter upgrades the system to 2S6M1, giving it thermals and a new missile.
The thermals for that upgrade are not listed.

**Comment by ImVexed** [comment]
https://github.com/ImVexed/ThunderView/commit/644f516901f30363c9cd084edc2c7dab88fcafff

Fixed, thanks for reporting!

**Comment by ginyat** [comment]
damn, that was quick
