### ISSUE TITLE
BR problems

### ISSUE THREAD

**Issue by Beafty** [ImVexed/ThunderView#23]
![image](https://user-images.githubusercontent.com/40541355/234666636-ee7cdd3b-2e10-4bed-a834-b83bc99a4ec2.png)
![image](https://user-images.githubusercontent.com/40541355/234666769-b4915539-ff28-4cdc-90ff-90a84d7a4c14.png)

**Comment by Beafty** [comment]
and 9 --->  9.0

**Comment by ImVexed** [comment]
Nice catch! Fixed: https://github.com/ImVexed/ThunderView/commit/5a21063373748a2620737c16cf72eaabd7880306
