### ISSUE TITLE
Maybe we can have helis thermals list?

### ISSUE THREAD

**Issue by Beafty** [ImVexed/ThunderView#24]
![image](https://user-images.githubusercontent.com/40541355/234864138-5294d8bb-19f2-48b2-b263-16450cb0b22a.png)
I just find theres something called Thermals 2+ 
![image](https://user-images.githubusercontent.com/40541355/234864246-f58aa593-9f80-42a3-ad8d-283fdac918e0.png)
but whole sheet have no 2+ or they just appear on helis?

**Comment by Beafty** [comment]
If so then can we get heli thermal list? thanks bro

**Comment by ImVexed** [comment]
https://thunderview.net/air-thermals/
https://github.com/ImVexed/ThunderView/commit/1f8d1977511324ea74b921317775fe2727fc071e
