### ISSUE TITLE
Missing missile

### ISSUE THREAD

**Issue by VojtaNN** [ImVexed/ThunderView#25]
![Snímek obrazovky 2023-05-13 204449](https://github.com/ImVexed/ThunderView/assets/61760213/45663d65-ff9f-4246-93c8-2c1079747b66)

Missing missile for Strela

![Snímek obrazovky 2023-05-13 204520](https://github.com/ImVexed/ThunderView/assets/61760213/b795364a-f052-496f-b2c0-0bf4c5e63d58)

**Comment by ImVexed** [comment]
Nice catch, we were actually missing a few missiles actually: https://github.com/ImVexed/ThunderView/commit/e72dc0bc6475c3717ce656a576234b7a0b2d2d70
