### ISSUE TITLE
9P149 Shturm-S Thermals

### ISSUE THREAD

**Issue by Ronald-Tagson** [ImVexed/ThunderView#26]
At the time of writing, the Thermals list has the Khrizantema listed with Thermals but the precursor Shturm-S doesn't have it listed, I've attached a proof as an image to this post. As far as I'm aware of it aswell, it's Gen 2 Thermals and well... some night vision 😆 
![image](https://github.com/ImVexed/ThunderView/assets/73474009/494c493f-e8dd-4eca-a505-4499bf6932c8)

**Comment by ImVexed** [comment]
Thank you for reporting this! I'll take a look at the files and see why it was missed.

**Comment by ImVexed** [comment]
Fixed in https://github.com/ImVexed/ThunderView/commit/1b1398100b20781d686ec2736cb3ca651e3352bd
This seems to have only affected the BMP-3, Shturm-S, and 2S6.
