### ISSUE TITLE
Т-90А font

### ISSUE THREAD

**Issue by Beafty** [ImVexed/ThunderView#30]
well its strange
![image](https://github.com/ImVexed/ThunderView/assets/40541355/c0d0fc7d-a310-47d6-b558-81e57ea9e558)
or its my problem?

**Comment by ImVexed** [comment]
That `A` isn't a normal. It's a `CYRILLIC CAPITAL LETTER A` which is unicode. and your font probably doesn't support Cyrillic so your browser is falling back to another font that does have unicode support.
